<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>tratamento de erros</title>
</head>
<body>
<script>
  // As declaraÃ§Ãµes "try...catch" marcam um bloco de declaraÃ§Ãµes para testar (try), e especifica uma resposta, caso uma exceÃ§Ã£o (erro) seja lanÃ§ada.
  
  
  
  // "try" executa uma ou mais declaraÃ§Ãµes para tratar algum provÃ¡vel erro (exceÃ§Ã£o), e, caso encontre, ele para imediatamente e envia a exceÃ§Ã£o para "catch" tratar.
  
  // "throw" gera uma exceÃ§Ã£o. | Ã‰ opcional.
  
  // "catch" contÃ©m declaraÃ§Ãµes que especificam o que fazer caso uma exceÃ§Ã£o (erro) seja lanÃ§ada do bloco "try".
  
  // "finally" Ã© executado depois que a declaraÃ§Ã£o "try" e "catch" sÃ£o executadas, independetemente se uma exceÃ§Ã£o (erro) foi lanÃ§ada ou nÃ£o. | Pode ser omitido.

  var num;
  try {
    num = prompt("Digite um valor");
    if (num > 10) {
      throw new Error("ðŸ›‘ O valor mÃ¡ximo Ã© 10. ðŸ›‘");
    }
  } catch (e) {
    console.log(e.message);
    num = 10;
    
    // e         ~> objeto
    // e.message ~> string
  } finally {
    document.write("Valor: " + num)
  }
  
</script>
</body>
</html>